version: '3'
services:
  nginx:
    image: nginx:1.22-alpine
    ports:
      - "443:443"
      - "8030:8030"
    volumes:
      - ./configdir:/etc/nginx/conf.d
      - ./certs:/etc/nginx/certs
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
